spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medical_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
