/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { medical } from './medical';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { ApiResponse_ArrayAssessmentReportResponse } from './models/ApiResponse_ArrayAssessmentReportResponse';
export type { ApiResponse_ArrayDashboardChartResponse } from './models/ApiResponse_ArrayDashboardChartResponse';
export type { ApiResponse_ArrayDeviceResponse } from './models/ApiResponse_ArrayDeviceResponse';
export type { ApiResponse_ArrayHealthWarningResponse } from './models/ApiResponse_ArrayHealthWarningResponse';
export type { ApiResponse_ArrayKeyPopulationResponse } from './models/ApiResponse_ArrayKeyPopulationResponse';
export type { ApiResponse_AssessmentReportResponse } from './models/ApiResponse_AssessmentReportResponse';
export type { ApiResponse_DashboardOverviewResponse } from './models/ApiResponse_DashboardOverviewResponse';
export type { ApiResponse_DeviceResponse } from './models/ApiResponse_DeviceResponse';
export type { ApiResponse_ElderlyProfileResponse } from './models/ApiResponse_ElderlyProfileResponse';
export type { ApiResponse_HealthWarningResponse } from './models/ApiResponse_HealthWarningResponse';
export type { ApiResponse_KeyPopulationResponse } from './models/ApiResponse_KeyPopulationResponse';
export type { ApiResponse_LoginResponse } from './models/ApiResponse_LoginResponse';
export type { ApiResponse_LoginUserInfo } from './models/ApiResponse_LoginUserInfo';
export type { ApiResponse_PageResult_AssessmentReportResponse } from './models/ApiResponse_PageResult_AssessmentReportResponse';
export type { ApiResponse_PageResult_DeviceResponse } from './models/ApiResponse_PageResult_DeviceResponse';
export type { ApiResponse_PageResult_ElderlyProfileResponse } from './models/ApiResponse_PageResult_ElderlyProfileResponse';
export type { ApiResponse_PageResult_HealthWarningResponse } from './models/ApiResponse_PageResult_HealthWarningResponse';
export type { ApiResponse_PageResult_KeyPopulationResponse } from './models/ApiResponse_PageResult_KeyPopulationResponse';
export type { ApiResponse_PageResult_UserResponse } from './models/ApiResponse_PageResult_UserResponse';
export type { ApiResponse_String } from './models/ApiResponse_String';
export type { ApiResponse_UserResponse } from './models/ApiResponse_UserResponse';
export type { ApiResponse_Void } from './models/ApiResponse_Void';
export type { AssessmentReportCreateRequest } from './models/AssessmentReportCreateRequest';
export type { AssessmentReportResponse } from './models/AssessmentReportResponse';
export type { bindingStatus } from './models/bindingStatus';
export type { careLevel } from './models/careLevel';
export type { DashboardChartResponse } from './models/DashboardChartResponse';
export type { DashboardOverviewResponse } from './models/DashboardOverviewResponse';
export type { DashboardSeriesItem } from './models/DashboardSeriesItem';
export type { DashboardTrendItem } from './models/DashboardTrendItem';
export type { DeviceBindRequest } from './models/DeviceBindRequest';
export type { DeviceResponse } from './models/DeviceResponse';
export type { DeviceUpdateRequest } from './models/DeviceUpdateRequest';
export type { elderlyId } from './models/elderlyId';
export type { elderlyIdOptional } from './models/elderlyIdOptional';
export type { ElderlyProfileCreateRequest } from './models/ElderlyProfileCreateRequest';
export type { ElderlyProfileResponse } from './models/ElderlyProfileResponse';
export type { ElderlyProfileUpdateRequest } from './models/ElderlyProfileUpdateRequest';
export type { endTime } from './models/endTime';
export type { gender } from './models/gender';
export type { HealthWarningHandleRequest } from './models/HealthWarningHandleRequest';
export type { HealthWarningQueryRequest } from './models/HealthWarningQueryRequest';
export type { HealthWarningResponse } from './models/HealthWarningResponse';
export type { id } from './models/id';
export type { KeyPopulationCreateRequest } from './models/KeyPopulationCreateRequest';
export type { KeyPopulationResponse } from './models/KeyPopulationResponse';
export type { KeyPopulationUpdateRequest } from './models/KeyPopulationUpdateRequest';
export type { keyword } from './models/keyword';
export type { LoginRequest } from './models/LoginRequest';
export type { LoginResponse } from './models/LoginResponse';
export type { LoginUserInfo } from './models/LoginUserInfo';
export type { onlineStatus } from './models/onlineStatus';
export type { pageNo } from './models/pageNo';
export type { PageResult_AssessmentReportResponse } from './models/PageResult_AssessmentReportResponse';
export type { PageResult_DeviceResponse } from './models/PageResult_DeviceResponse';
export type { PageResult_ElderlyProfileResponse } from './models/PageResult_ElderlyProfileResponse';
export type { PageResult_HealthWarningResponse } from './models/PageResult_HealthWarningResponse';
export type { PageResult_KeyPopulationResponse } from './models/PageResult_KeyPopulationResponse';
export type { PageResult_UserResponse } from './models/PageResult_UserResponse';
export type { pageSize } from './models/pageSize';
export type { PasswordChangeRequest } from './models/PasswordChangeRequest';
export type { regionCode } from './models/regionCode';
export type { severity } from './models/severity';
export type { source } from './models/source';
export type { startTime } from './models/startTime';
export type { status } from './models/status';
export type { UserCreateRequest } from './models/UserCreateRequest';
export type { UserResponse } from './models/UserResponse';
export type { UserStatusUpdateRequest } from './models/UserStatusUpdateRequest';
export type { UserUpdateRequest } from './models/UserUpdateRequest';
export type { warningType } from './models/warningType';

export { AssessmentReportService } from './services/AssessmentReportService';
export { AuthService } from './services/AuthService';
export { DashboardService } from './services/DashboardService';
export { DeviceService } from './services/DeviceService';
export { DoctorAccountService } from './services/DoctorAccountService';
export { ElderlyAccountService } from './services/ElderlyAccountService';
export { ElderlyProfileService } from './services/ElderlyProfileService';
export { HealthWarningService } from './services/HealthWarningService';
export { KeyPopulationService } from './services/KeyPopulationService';
export { ReportStatisticsService } from './services/ReportStatisticsService';
export { UserAccountService } from './services/UserAccountService';
