/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { medical } from './medical';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AnalysisRequest } from './models/AnalysisRequest';
export type { AnalysisResult } from './models/AnalysisResult';
export type { ApiAnalysis } from './models/ApiAnalysis';
export type { ApiAnalysisList } from './models/ApiAnalysisList';
export type { ApiAssessmentReport } from './models/ApiAssessmentReport';
export type { ApiAssessmentReportList } from './models/ApiAssessmentReportList';
export type { ApiAssessmentReportPage } from './models/ApiAssessmentReportPage';
export type { ApiBase } from './models/ApiBase';
export type { ApiChartList } from './models/ApiChartList';
export type { ApiDashboardOverview } from './models/ApiDashboardOverview';
export type { ApiDevice } from './models/ApiDevice';
export type { ApiDeviceList } from './models/ApiDeviceList';
export type { ApiDevicePage } from './models/ApiDevicePage';
export type { ApiDeviceReport } from './models/ApiDeviceReport';
export type { ApiDeviceReportList } from './models/ApiDeviceReportList';
export type { ApiElderly } from './models/ApiElderly';
export type { ApiElderlyPage } from './models/ApiElderlyPage';
export type { ApiEmpty } from './models/ApiEmpty';
export type { ApiErrorResponse } from './models/ApiErrorResponse';
export type { ApiKeyPopulation } from './models/ApiKeyPopulation';
export type { ApiKeyPopulationList } from './models/ApiKeyPopulationList';
export type { ApiKeyPopulationPage } from './models/ApiKeyPopulationPage';
export type { ApiLogin } from './models/ApiLogin';
export type { ApiStatisticsOverview } from './models/ApiStatisticsOverview';
export type { ApiTodoList } from './models/ApiTodoList';
export type { ApiUser } from './models/ApiUser';
export type { ApiUserPage } from './models/ApiUserPage';
export type { ApiWarning } from './models/ApiWarning';
export type { ApiWarningList } from './models/ApiWarningList';
export type { ApiWarningPage } from './models/ApiWarningPage';
export type { AssessmentReport } from './models/AssessmentReport';
export type { AssessmentReportCreateRequest } from './models/AssessmentReportCreateRequest';
export type { AssessmentReportPage } from './models/AssessmentReportPage';
export type { AssessmentReportReviewRequest } from './models/AssessmentReportReviewRequest';
export type { AssessmentReportUpdateRequest } from './models/AssessmentReportUpdateRequest';
export type { ChangePasswordRequest } from './models/ChangePasswordRequest';
export type { DashboardChart } from './models/DashboardChart';
export type { DashboardOverview } from './models/DashboardOverview';
export type { Device } from './models/Device';
export type { DeviceBindRequest } from './models/DeviceBindRequest';
export type { DeviceCreateRequest } from './models/DeviceCreateRequest';
export type { DeviceDataReport } from './models/DeviceDataReport';
export type { DeviceDataReportRequest } from './models/DeviceDataReportRequest';
export type { DevicePage } from './models/DevicePage';
export type { DeviceUpdateRequest } from './models/DeviceUpdateRequest';
export type { ElderlyPage } from './models/ElderlyPage';
export type { ElderlyProfile } from './models/ElderlyProfile';
export type { ElderlyProfileCreateRequest } from './models/ElderlyProfileCreateRequest';
export type { ElderlyProfileUpdateRequest } from './models/ElderlyProfileUpdateRequest';
export type { HealthWarning } from './models/HealthWarning';
export type { HealthWarningAssignRequest } from './models/HealthWarningAssignRequest';
export type { HealthWarningCreateRequest } from './models/HealthWarningCreateRequest';
export type { HealthWarningHandleRequest } from './models/HealthWarningHandleRequest';
export type { Id } from './models/Id';
export type { KeyPopulation } from './models/KeyPopulation';
export type { KeyPopulationCreateRequest } from './models/KeyPopulationCreateRequest';
export type { KeyPopulationPage } from './models/KeyPopulationPage';
export type { KeyPopulationUpdateRequest } from './models/KeyPopulationUpdateRequest';
export type { Keyword } from './models/Keyword';
export type { LoginRequest } from './models/LoginRequest';
export type { LoginResult } from './models/LoginResult';
export type { LoginUserInfo } from './models/LoginUserInfo';
export type { LogoutRequest } from './models/LogoutRequest';
export type { PageNo } from './models/PageNo';
export type { PageSize } from './models/PageSize';
export type { PasswordRequest } from './models/PasswordRequest';
export type { ProfileUpdateRequest } from './models/ProfileUpdateRequest';
export type { RefreshTokenRequest } from './models/RefreshTokenRequest';
export type { RegisterRequest } from './models/RegisterRequest';
export type { RoleAssignRequest } from './models/RoleAssignRequest';
export type { RoleCode } from './models/RoleCode';
export type { SpecializedUserCreateRequest } from './models/SpecializedUserCreateRequest';
export type { StatisticsOverview } from './models/StatisticsOverview';
export type { Todo } from './models/Todo';
export type { User } from './models/User';
export type { UserCreateRequest } from './models/UserCreateRequest';
export type { UserPage } from './models/UserPage';
export type { UserStatusUpdateRequest } from './models/UserStatusUpdateRequest';
export type { UserUpdateRequest } from './models/UserUpdateRequest';
export type { WarningPage } from './models/WarningPage';

export { AiAnalysisService } from './services/AiAnalysisService';
export { AssessmentReportService } from './services/AssessmentReportService';
export { AuthService } from './services/AuthService';
export { DashboardService } from './services/DashboardService';
export { DeviceService } from './services/DeviceService';
export { DoctorAccountService } from './services/DoctorAccountService';
export { ElderlyAccountService } from './services/ElderlyAccountService';
export { ElderlyProfileService } from './services/ElderlyProfileService';
export { HealthWarningService } from './services/HealthWarningService';
export { KeyPopulationService } from './services/KeyPopulationService';
export { ProfileService } from './services/ProfileService';
export { ReportStatisticsService } from './services/ReportStatisticsService';
export { UserAccountService } from './services/UserAccountService';
